const { nanoid } = require('nanoid');

const shopItems = [
  {
    id: nanoid(16),
    category: 'kendaraan',
    imageUrl: 'images/shopImages/kendaraan/sepeda.jpg',
    itemName: 'Sepeda',
    description: 'Sepeda dalam kondisi baik, ideal untuk petualangan off-road.',
    price: 1500000,
  },
  {
    id: nanoid(16),
    category: 'kendaraan',
    imageUrl: 'images/shopImages/kendaraan/motor.jpg',
    itemName: 'Motor',
    description: 'Motor dalam kondisi baik, sporty dan bertenaga untuk perjalanan sehari-hari.',
    price: 1500000,
  },
  {
    id: nanoid(16),
    category: 'kendaraan',
    imageUrl: 'images/shopImages/kendaraan/mobil.jpeg',
    itemName: 'Mobil',
    description: 'Mobil dalam kondisi baik, ruang luas dan nyaman untuk keluarga Anda.',
    price: 150000000,
  },
  {
    id: nanoid(16),
    category: 'elektronik',
    imageUrl: 'images/shopImages/elektronik/televisi.jpeg',
    itemName: 'TV Bekas',
    description: 'TV dalam kondisi baik, gambar jernih, dan siap menghibur keluarga Anda.',
    price: 2500000,
  },
  {
    id: nanoid(16),
    category: 'elektronik',
    imageUrl: 'images/shopImages/elektronik/handphone.jpg',
    itemName: 'Hp second',
    description: 'Hp dalam kondisi baik, dengan performa dan kamera mumpuni.',
    price: 2000000,
  },
  {
    id: nanoid(16),
    category: 'elektronik',
    imageUrl: 'images/shopImages/elektronik/leptop.jpeg',
    itemName: 'Leptop second',
    description: 'Laptop ini dalam kondisi baik, ideal untuk pekerjaan dan hiburan.',
    price: 3000000,
  },
  {
    id: nanoid(16),
    category: 'elektronik',
    imageUrl: 'images/shopImages/elektronik/kipas-angin.jpeg',
    itemName: 'Kipas second',
    description: 'Kipas angin dalam kondisi baik, efektif untuk sirkulasi udara.',
    price: 150000,
  },
  {
    id: nanoid(16),
    category: 'elektronik',
    imageUrl: 'images/shopImages/elektronik/mesin-cuci.jpeg',
    itemName: 'Mesin cuci second',
    description: 'Mesin cuci dalam kondisi baik, efisien untuk kebutuhan rumah tangga.',
    price: 1500000,
  },
  {
    id: nanoid(16),
    category: 'pakaian',
    imageUrl: 'images/shopImages/pakaian/hoodie.jpg',
    itemName: 'Hoodie Second',
    description: 'hoodie dalam kondisi baik, nyaman dan stylish.',
    price: 75000,
  },
  {
    id: nanoid(16),
    category: 'pakaian',
    imageUrl: 'images/shopImages/pakaian/baju.jpg',
    itemName: 'Baju Second',
    description: 'Baju dalam kondisi baik, modern dan nyaman dipakai.',
    price: 55000,
  },
  {
    id: nanoid(16),
    category: 'pakaian',
    imageUrl: 'images/shopImages/pakaian/celana-levis.jpg',
    itemName: 'Celana levis Second',
    description: 'Celana Levis dalam kondisi baik, klasik dan nyaman.',
    price: 65000,
  },
  {
    id: nanoid(16),
    category: 'pakaian',
    imageUrl: 'images/shopImages/pakaian/celana-pendek.jpeg',
    itemName: 'Celana pendek Second',
    description: 'Celana pendek dalam kondisi baik, cocok untuk cuaca hangat.',
    price: 35000,
  },
  {
    id: nanoid(16),
    category: 'pakaian',
    imageUrl: 'images/shopImages/pakaian/jaket.jpeg',
    itemName: 'Jaket Second',
    description: 'Jaket dalam kondisi baik, sporty dan nyaman.',
    price: 75000,
  },
  {
    id: nanoid(16),
    category: 'pakaian',
    imageUrl: 'images/shopImages/pakaian/kemeja.jpg',
    itemName: 'Kemeja Second',
    description: 'Kemeja dalam kondisi baik, rapi dan stylish.',
    price: 65000,
  },
];

module.exports = shopItems;
